[debug] [2024-07-31T14:24:34.347Z] ----------------------------------------------------------------------
[debug] [2024-07-31T14:24:34.351Z] Command:       C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\firebase-tools\lib\bin\firebase.js deploy --only functions --debug
[debug] [2024-07-31T14:24:34.352Z] CLI Version:   13.14.2
[debug] [2024-07-31T14:24:34.352Z] Platform:      win32
[debug] [2024-07-31T14:24:34.352Z] Node Version:  v18.20.4
[debug] [2024-07-31T14:24:34.354Z] Time:          Wed Jul 31 2024 11:24:34 GMT-0300 (Horário Padrão de Brasília)
[debug] [2024-07-31T14:24:34.354Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-07-31T14:24:34.482Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2024-07-31T14:24:34.485Z] > authorizing via signed-in user (gabriel@sistemap.com.br)
[debug] [2024-07-31T14:24:34.486Z] [iam] checking project supabasefunction-a65f5 for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
[debug] [2024-07-31T14:24:34.491Z] > refreshing access token with scopes: []
[debug] [2024-07-31T14:24:34.495Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-07-31T14:24:34.495Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-07-31T14:24:55.685Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------523458936975622883635673","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 2800:3f0:4001:822::200a:443
[debug] [2024-07-31T14:24:55.687Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2024-07-31T14:24:55.688Z] > refreshing access token with scopes: []
[debug] [2024-07-31T14:24:55.691Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-07-31T14:24:55.692Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-07-31T14:25:16.737Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------870917275132886914513634","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 2800:3f0:4001:822::200a:443
[debug] [2024-07-31T14:25:16.744Z] [functions] service account IAM check errored, deploy may fail: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci {"name":"FirebaseError","children":[],"exit":1,"message":"Authentication Error: Your credentials are no longer valid. Please run \u001b[1mfirebase login --reauth\u001b[22m\n\nFor CI servers and headless environments, generate a new token with \u001b[1mfirebase login:ci\u001b[22m","status":500}
[info] 
[info] === Deploying to 'supabasefunction-a65f5'...
[info] 
[info] i  deploying functions 
[debug] [2024-07-31T14:25:16.753Z] > refreshing access token with scopes: []
[debug] [2024-07-31T14:25:16.761Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-07-31T14:25:16.762Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-07-31T14:25:34.096Z] ----------------------------------------------------------------------
[debug] [2024-07-31T14:25:34.102Z] Command:       C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\firebase-tools\lib\bin\firebase.js login --reauth
[debug] [2024-07-31T14:25:34.103Z] CLI Version:   13.14.2
[debug] [2024-07-31T14:25:34.103Z] Platform:      win32
[debug] [2024-07-31T14:25:34.103Z] Node Version:  v18.20.4
[debug] [2024-07-31T14:25:34.106Z] Time:          Wed Jul 31 2024 11:25:34 GMT-0300 (Horário Padrão de Brasília)
[debug] [2024-07-31T14:25:34.107Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=842153005&redirect_uri=http%3A%2F%2Flocalhost%3A9005&login_hint=gabriel%40sistemap.com.br
[info] 
[info] Waiting for authentication...
[debug] [2024-07-31T14:25:51.178Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[debug] [2024-07-31T14:25:51.179Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[debug] [2024-07-31T14:26:12.311Z] *** [apiv2] error from fetch(https://accounts.google.com/o/oauth2/token, {"headers":{},"method":"POST","body":{"_overheadLength":543,"_valueLength":208,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------917746499752191560570297","_events":{},"_eventsCount":1}}): FetchError: request to https://accounts.google.com/o/oauth2/token failed, reason: connect ETIMEDOUT 2800:3f0:4003:c02::54:443
[debug] [2024-07-31T14:26:12.312Z] Token Fetch Error: FirebaseError: Failed to make request to https://accounts.google.com/o/oauth2/token
    at RetryOperation._fn (C:\Users\maria\AppData\Roaming\nvm\v18.20.4\node_modules\firebase-tools\lib\apiv2.js:259:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [2024-07-31T14:26:12.349Z] >>> [apiv2][query] POST https://auth.firebase.tools/attest [none]
[debug] [2024-07-31T14:26:12.351Z] >>> [apiv2][body] POST https://auth.firebase.tools/attest {"session_id":"5cfe2fad-6c86-4ed1-866b-3d3d86667575"}
[debug] [2024-07-31T14:26:37.671Z] ----------------------------------------------------------------------
[debug] [2024-07-31T14:26:37.675Z] Command:       C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\firebase-tools\lib\bin\firebase.js login --reauth
[debug] [2024-07-31T14:26:37.676Z] CLI Version:   13.14.2
[debug] [2024-07-31T14:26:37.676Z] Platform:      win32
[debug] [2024-07-31T14:26:37.676Z] Node Version:  v18.20.4
[debug] [2024-07-31T14:26:37.678Z] Time:          Wed Jul 31 2024 11:26:37 GMT-0300 (Horário Padrão de Brasília)
[debug] [2024-07-31T14:26:37.678Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=681009406&redirect_uri=http%3A%2F%2Flocalhost%3A9005&login_hint=gabriel%40sistemap.com.br
[info] 
[info] Waiting for authentication...
[debug] [2024-07-31T14:27:02.079Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[debug] [2024-07-31T14:27:02.080Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[debug] [2024-07-31T14:27:23.200Z] *** [apiv2] error from fetch(https://accounts.google.com/o/oauth2/token, {"headers":{},"method":"POST","body":{"_overheadLength":543,"_valueLength":208,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------493631865116443718519266","_events":{},"_eventsCount":1}}): FetchError: request to https://accounts.google.com/o/oauth2/token failed, reason: connect ETIMEDOUT 2800:3f0:4003:c02::54:443
[debug] [2024-07-31T14:27:23.202Z] Token Fetch Error: FirebaseError: Failed to make request to https://accounts.google.com/o/oauth2/token
    at RetryOperation._fn (C:\Users\maria\AppData\Roaming\nvm\v18.20.4\node_modules\firebase-tools\lib\apiv2.js:259:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [2024-07-31T14:27:23.215Z] >>> [apiv2][query] POST https://auth.firebase.tools/attest [none]
[debug] [2024-07-31T14:27:23.216Z] >>> [apiv2][body] POST https://auth.firebase.tools/attest {"session_id":"4a2bd9a1-18b4-48d6-bb15-784f455dfdec"}
[debug] [2024-07-31T14:27:47.472Z] ----------------------------------------------------------------------
[debug] [2024-07-31T14:27:47.476Z] Command:       C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\firebase-tools\lib\bin\firebase.js login:ci
[debug] [2024-07-31T14:27:47.477Z] CLI Version:   13.14.2
[debug] [2024-07-31T14:27:47.477Z] Platform:      win32
[debug] [2024-07-31T14:27:47.477Z] Node Version:  v18.20.4
[debug] [2024-07-31T14:27:47.479Z] Time:          Wed Jul 31 2024 11:27:47 GMT-0300 (Horário Padrão de Brasília)
[debug] [2024-07-31T14:27:47.479Z] ----------------------------------------------------------------------
[debug] 
[warn] !  Authenticating with a `login:ci` token is deprecated and will be removed in a future major version of `firebase-tools`. Instead, use a service account key with `GOOGLE_APPLICATION_CREDENTIALS`: https://cloud.google.com/docs/authentication/getting-started 
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=230652797&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2024-07-31T14:28:01.635Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[debug] [2024-07-31T14:28:01.635Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[debug] [2024-07-31T14:28:22.733Z] *** [apiv2] error from fetch(https://accounts.google.com/o/oauth2/token, {"headers":{},"method":"POST","body":{"_overheadLength":543,"_valueLength":208,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------243940504800277227953128","_events":{},"_eventsCount":1}}): FetchError: request to https://accounts.google.com/o/oauth2/token failed, reason: connect ETIMEDOUT 2800:3f0:4003:c02::54:443
[debug] [2024-07-31T14:28:22.735Z] Token Fetch Error: FirebaseError: Failed to make request to https://accounts.google.com/o/oauth2/token
    at RetryOperation._fn (C:\Users\maria\AppData\Roaming\nvm\v18.20.4\node_modules\firebase-tools\lib\apiv2.js:259:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [2024-07-31T14:28:22.751Z] >>> [apiv2][query] POST https://auth.firebase.tools/attest [none]
[debug] [2024-07-31T14:28:22.752Z] >>> [apiv2][body] POST https://auth.firebase.tools/attest {"session_id":"46b85b0a-daa2-4692-ae18-2cc453ff3061"}
[debug] [2024-07-31T14:28:36.383Z] ----------------------------------------------------------------------
[debug] [2024-07-31T14:28:36.387Z] Command:       C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2024-07-31T14:28:36.388Z] CLI Version:   13.14.2
[debug] [2024-07-31T14:28:36.388Z] Platform:      win32
[debug] [2024-07-31T14:28:36.388Z] Node Version:  v18.20.4
[debug] [2024-07-31T14:28:36.390Z] Time:          Wed Jul 31 2024 11:28:36 GMT-0300 (Horário Padrão de Brasília)
[debug] [2024-07-31T14:28:36.390Z] ----------------------------------------------------------------------
[debug] 
[info] Already logged in as gabriel@sistemap.com.br
[debug] [2024-07-31T14:28:46.633Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\maria\AppData\Roaming\nvm\v18.20.4\node_modules\firebase-tools\lib\utils.js:268:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
